# Workflow: Deploys network stack only
name: Deploy Network Stack

# Trigger: Runs when code is pushed to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Runner: GitHub-hosted Ubuntu environment
    runs-on: ubuntu-latest
    steps:
      # Step: Check out repository code to access files
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Verify template file exists
      - name: Check template file
        run: |
          ls -l templates/network-stack.cf.yml || echo "Error: Template file not found"
          if [ ! -f templates/network-stack.cf.yml ]; then exit 1; fi

      # Step: Configure AWS CLI with credentials from secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS access key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS secret key
          aws-region: us-east-1 # Set region to us-east-1

      # Step: Check AWS CLI setup
      - name: Verify AWS CLI
        run: |
          aws --version # Print AWS CLI version
          aws sts get-caller-identity # Verify credentials work

      # Step: Deploy network stack using CloudFormation
      - name: Deploy CloudFormation network stack
        run: aws cloudformation deploy --template-file templates/network-stack.cf.yml --stack-name ecs-network-stack --region us-east-1