# This workflow updates the ECS App stack when changes are made to the CloudFormation template.
name: Update ECS App Stack

on:
  push:
    branches:
      - main
    paths:
      - 'templates/ecs-stack.cf.yml'

jobs:
  update-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update CloudFormation stack
        run: |
          aws cloudformation update-stack \\
            --stack-name ecs-app-stack \\
            --template-body file://templates/ecs-stack.cf.yml \\
            --parameters \\
              ParameterKey=VPCId,UsePreviousValue=true \\
              ParameterKey=PublicSubnet1,UsePreviousValue=true \\
              ParameterKey=PublicSubnet2,UsePreviousValue=true \\
              ParameterKey=PrivateSubnet1,UsePreviousValue=true \\
              ParameterKey=PrivateSubnet2,UsePreviousValue=true \\
              ParameterKey=SecurityGroupId,UsePreviousValue=true \\
              ParameterKey=ECRRepositoryUri,UsePreviousValue=true \\
            --capabilities CAPABILITY_IAM \\
            --region us-east-1

      - name: Wait for stack update
        run: |
          aws cloudformation wait stack-update-complete \\
            --stack-name ecs-app-stack \\
            --region us-east-1
EOL